int toto (int i)
{
  //27
  i + 27
}
//
//
//int test ()
//{
//  // let int i = 3;
//  //  let int j = i;
//  //  3;
//  let int i = 3;
//  let int j = 4;
//  let int k = 5;
//  //  3;
//  //  (4 + i) + toto (2)
////  ((4 + i) + (i + 3)) + 
//
//
//  (1 + i) + ((1 + i) + ((1 + i) + ((1 + i) + toto (2)))) / 2;
//
//  i = j = k;
// test_function (i);
// test_function (j);
// 3
////(1 + i) + ((1 + i) + ((1 + i) + ((1 + i) + toto (2)))) 
//
////  ((1 + i) + ((1 + i) + ((1 + i) + toto (2))))
//  // 4 + i + toto (2)
//
//}

int test ()
{
  let int i = 4;
  let int j = 5;

  let Symbol truc = 'test';

//  toto (truc);
  
//   4 + toto (2)
//   i + j + i
  

   1 + j;
   1 + j;
  

   //   4 + { let int i = toto (2);
   //         i };

   (1 + i) + ((1 + i) + ((1 + i) + ((1 + i) + j)))
//  ((1 + i) + ((1 + i) + ((1 + i) + j))) 
 // 4 + 3
   //     i + 3 + j
   // i + j 
}
